# 4 NumPy基础：数组和矢量运算

## 4.0 Intro

通过考察一个包含一百万整数的数组，和一个等价的Python列表，体现NumPy在处理大数组数据方面的高效。

In [1]:
import numpy as np

my_arr = np.arange(1000000) # 包含一百万整数的数组
my_list = list(range(1000000)) # 等价的Python列表

各个序列分别乘以2：

In [2]:
%time for _ in range(10): my_arr2 = my_arr * 2

Wall time: 35.1 ms


In [3]:
%time for _ in range(10): my_list2 = [x * 2 for x in my_list]

Wall time: 985 ms


> **笔记：**基于NumPy的算法要比纯Python快10到100倍（甚至更快），并且使用的内存更少。

## 4.1 NumPy的ndarray：一种多维数组对象

### 4.1.0 Intro

NumPy最重要的一个特点就是其N维数组对象（即ndarray），该对象是一个快速而灵活的大数据集容器。你可以利用这种数组对整块数据执行一些数学运算，其语法跟标量元素之间的运算一样。

要明白Python是如何利用与标量值类似的语法进行批次计算，首先引入NumPy，然后生成一个包含随机数据的小数组：

In [4]:
import numpy as np

# 生成一个包含随机数据的小数组
data = np.random.randn(2, 3)
data

array([[ 0.53264644, -0.12829133, -0.13663357],
       [-0.02135962, -1.10810789,  0.02476846]])

然后进行数学运算：

In [5]:
data * 10 # 数组中所有元素都乘以10

array([[  5.32646442,  -1.2829133 ,  -1.36633572],
       [ -0.2135962 , -11.08107888,   0.24768461]])

In [6]:
data + data # 数组中的每个元素与自身相加

array([[ 1.06529288, -0.25658266, -0.27326714],
       [-0.04271924, -2.21621578,  0.04953692]])

ndarray是一个通用的同构数据多维容器，也就是说，其中的所有元素必须是相同类型的。每个数组都有一个shape（一个表示各维度大小的元组）和一个dtype（一个用于说明数组数据类型的对象）：

In [7]:
data.shape # 表示数组各维度大小

(2, 3)

In [8]:
data.dtype # 说明数组数据类型的对象

dtype('float64')

### 4.1.1 创建ndarray

创建数组最简单的办法就是使用**array函数**。它接受一切序列型的对象（包括其他数组），然后产生一个新的含有传入数据的NumPy数组。以一个列表的转换为例：

In [9]:
data1 = [6, 7.5, 8, 0, 1]

arr1 = np.array(data1) # 转换为数组
arr1

array([6. , 7.5, 8. , 0. , 1. ])

嵌套序列（比如由一组等长列表组成的列表）将会被转换为一个多维数组：

In [10]:
data2 = [[1, 2, 3, 4], [5, 6, 7, 8]]

arr2 = np.array(data2)
arr2

array([[1, 2, 3, 4],
       [5, 6, 7, 8]])

因为data2是列表的列表，NumPy数组arr2的两个维度的shape是从data2引入的。可以用属性ndim和shape验证：

In [11]:
arr2.ndim

2

In [12]:
arr2.shape

(2, 4)

除非特别说明（稍后将会详细介绍），np.array会尝试为新建的这个数组推断出一个较为合适的数据类型。数据类型保存在一个特殊的dtype对象中。比如说，在上面的两个例子中，我们有：

In [13]:
arr1.dtype

dtype('float64')

In [14]:
arr2.dtype

dtype('int32')

除np.array之外，还有一些函数也可以新建数组。比如，zeros和ones分别可以创建指定长度或形状的全0或全1数组。empty可以创建一个没有任何具体值的数组。要用这些方法创建多维数组，只需传入一个表示形状的元组即可：

In [15]:
np.zeros(10)

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

In [16]:
np.zeros((3, 6))

array([[0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0.]])

In [17]:
np.empty((2, 3, 2))

array([[[1.08521483e-311, 3.16202013e-322],
        [0.00000000e+000, 0.00000000e+000],
        [1.35807731e-312, 1.93466174e+184]],

       [[9.60431911e-071, 2.21649686e-056],
        [2.09028777e-076, 7.60936381e-042],
        [3.70230879e-033, 5.49575801e+174]]])

> **注意：**认为`np.empty`会返回全0数组的想法是不安全的。很多情况下（如前所示），它返回的都是一些未初始化的垃圾值。

arange是Python内置函数range的数组版：

In [18]:
np.arange(10)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

下表列出了一些数组创建函数。由于NumPy关注的是数值计算，因此，如果没有特别指定，数据类型基本都是float64（浮点数）：
![数组创建函数](https://upload-images.jianshu.io/upload_images/7178691-78ab11f67e7077a6.png?imageMogr2/auto-orient/strip%7CimageView2/2/w/696)

### 4.1.2 ndarray的数据类型

dtype（数据类型）是一个特殊的对象，它含有ndarray将一块内存解释为特定数据类型所需的信息：

In [19]:
arr1 = np.array([1, 2, 3], dtype=np.float64)
arr2 = np.array([1, 2, 3], dtype=np.int32)

In [20]:
arr1.dtype

dtype('float64')

In [21]:
arr2.dtype

dtype('int32')

dtype是NumPy灵活交互其它系统的源泉之一。多数情况下，它们直接映射到相应的机器表示，这使得“读写磁盘上的二进制数据流”以及“集成低级语言代码（如C、Fortran）”等工作变得更加简单。数值型dtype的命名方式相同：一个类型名（如float或int），后面跟一个用于表示各元素位长的数字。标准的双精度浮点值（即Python中的float对象）需要占用8字节（即64位）。因此，该类型在NumPy中就记作float64。下表列出了NumPy所支持的全部数据类型：

![NumPy的数据类型](https://upload-images.jianshu.io/upload_images/7178691-2f2d7406a8bc076c.png?imageMogr2/auto-orient/strip%7CimageView2/2/w/700)
![NumPy的数据类型](https://upload-images.jianshu.io/upload_images/7178691-5cc31115615737b7.png?imageMogr2/auto-orient/strip%7CimageView2/2/w/700)

> **笔记：**记不住这些NumPy的dtype也没关系，新手更是如此。通常只需要知道你所处理的数据的大致类型是浮点数、复数、整数、布尔值、字符串，还是普通的Python对象即可。当你需要控制数据在内存和磁盘中的存储方式时（尤其是对大数据集），那就得了解如何控制存储类型。

你可以通过ndarray的astype方法明确地将一个数组从一个dtype转换成另一个dtype：

In [22]:
arr = np.array([1, 2, 3, 4, 5])

arr.dtype

dtype('int32')

In [23]:
float_arr = arr.astype(np.float64) # 转换dtype

float_arr.dtype

dtype('float64')

In [24]:
arr = np.array([3.7, -1.2, -2.6, 0.5, 12.9, 10.1]) # 创建一个浮点数数组
arr

array([ 3.7, -1.2, -2.6,  0.5, 12.9, 10.1])

In [25]:
arr.astype(np.int32) # 将浮点数转换成整数

array([ 3, -1, -2,  0, 12, 10])

In [26]:
numeric_strings = np.array(['1.25', '-9.6', '42'], dtype=np.string_) # 创建一个字符串数组
numeric_strings.astype(float) # 将字符串转换为浮点数

array([ 1.25, -9.6 , 42.  ])

> **注意：**使用numpy.string_类型时，一定要小心，因为NumPy的字符串数据是大小固定的，发生截取时，不会发出警告。pandas提供了更多非数值数据的便利的处理方法。

数组的`dtype`还有另一个属性：

In [27]:
int_array = np.arange(10)
calibers = np.array([.22, .270, .357, .380, .44, .50], dtype=np.float64)

int_array.astype(calibers.dtype)

array([0., 1., 2., 3., 4., 5., 6., 7., 8., 9.])

你还可以用简洁的类型代码来表示`dtype`：

In [28]:
empty_uint32 = np.empty(8, dtype='u4')
empty_uint32

array([         0, 1075314688,          0, 1075707904,          0,
       1075838976,          0, 1072693248], dtype=uint32)

> **笔记：**调用`astype`总会创建一个新的数组（一个数据的备份），即使新的`dtype`与旧的`dtype`相同。

### 4.1.3 NumPy数组的运算

数组很重要，因为它使你不用编写循环即可对数据执行批量运算。NumPy用户称其为矢量化（vectorization）。大小相等的数组之间的任何算术运算都会将运算应用到元素级：

In [29]:
arr = np.array([[1., 2., 3.], [4., 5., 6.]])
arr

array([[1., 2., 3.],
       [4., 5., 6.]])

In [30]:
arr * arr

array([[ 1.,  4.,  9.],
       [16., 25., 36.]])

In [31]:
arr - arr

array([[0., 0., 0.],
       [0., 0., 0.]])

数组与标量的算术运算会将标量值传播到各个元素：

In [32]:
1 / arr

array([[1.        , 0.5       , 0.33333333],
       [0.25      , 0.2       , 0.16666667]])

In [33]:
arr ** 0.5

array([[1.        , 1.41421356, 1.73205081],
       [2.        , 2.23606798, 2.44948974]])

大小相同的数组之间的比较会生成布尔值数组：

In [34]:
arr2 = np.array([[0., 4., 1.], [7., 2., 12.]])
arr2

array([[ 0.,  4.,  1.],
       [ 7.,  2., 12.]])

In [35]:
arr2 > arr

array([[False,  True, False],
       [ True, False,  True]])

不同大小的数组之间的运算叫做广播（broadcasting）。

### 4.1.4 基本的索引和切片

NumPy数组的索引是一个内容丰富的主题，因为选取数据子集或单个元素的方式有很多。一维数组很简单。从表面上看，它们跟Python列表的功能差不多：

In [36]:
arr = np.arange(10)
arr

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [37]:
arr[5]

5

In [38]:
arr[5:8]

array([5, 6, 7])

In [39]:
arr[5:8] = 12
arr

array([ 0,  1,  2,  3,  4, 12, 12, 12,  8,  9])

如上所示，当你将一个标量值赋值给一个切片时（如`arr[5:8]=12`），该值会自动传播（也就说后面将会讲到的“广播”）到整个选区。跟列表最重要的区别在于，数组切片是原始数组的视图。这意味着数据不会被复制，视图上的任何修改都会直接反映到源数组上。

In [40]:
arr_slice = arr[5:8]
arr_slice

array([12, 12, 12])

修改`arr_slice`中的值，变动也会体现在原始数组`arr`中：

In [41]:
arr_slice[1] = 12345
arr

array([    0,     1,     2,     3,     4,    12, 12345,    12,     8,
           9])

切片`[ : ]`会给数组中的所有值赋值：

In [42]:
arr_slice[:] = 64
arr

array([ 0,  1,  2,  3,  4, 64, 64, 64,  8,  9])

如果你刚开始接触NumPy，可能会对此感到惊讶（尤其是当你曾经用过其他热衷于复制数组数据的编程语言）。由于NumPy的设计目的是处理大数据，所以你可以想象一下，假如NumPy坚持要将数据复制来复制去的话会产生何等的性能和内存问题。

> **注意：**如果你想要得到的是ndarray切片的一份副本而非视图，就需要明确地进行复制操作，例如`arr[5:8].copy()`。

对于高维度数组，能做的事情更多。在一个二维数组中，各索引位置上的元素不再是标量而是一维数组：

In [43]:
arr2d = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])
arr2d[2]

array([7, 8, 9])

因此，可以对各个元素进行递归访问，但这样需要做的事情有点多。你可以传入一个以逗号隔开的索引列表来选取单个元素。也就是说，下面两种方式是等价的：

In [44]:
arr2d[0][2]

3

In [45]:
arr2d[0, 2]

3

下图说明了二维数组的索引方式。轴0作为行，轴1作为列：

![NumPy数组中的元素索引](https://upload-images.jianshu.io/upload_images/7178691-0a641536f73f560e.png?imageMogr2/auto-orient/strip%7CimageView2/2/w/700)

在多维数组中，如果省略了后面的索引，则返回对象会是一个维度低一点的ndarray（它含有高一级维度上的所有数据）。因此，在2×2×3数组`arr3d`中：

In [46]:
arr3d = np.array([[[1, 2, 3], [4, 5, 6]], [[7, 8, 9], [10, 11, 12]]])
arr3d

array([[[ 1,  2,  3],
        [ 4,  5,  6]],

       [[ 7,  8,  9],
        [10, 11, 12]]])

`arr3d[0]`是一个2×3数组：

In [47]:
arr3d[0]

array([[1, 2, 3],
       [4, 5, 6]])

标量值和数组都可以被赋值给`arr3d[0]`：

In [48]:
old_values = arr3d[0].copy()

In [49]:
arr3d[0] = 42
arr3d

array([[[42, 42, 42],
        [42, 42, 42]],

       [[ 7,  8,  9],
        [10, 11, 12]]])

In [50]:
arr3d[0] = old_values
arr3d

array([[[ 1,  2,  3],
        [ 4,  5,  6]],

       [[ 7,  8,  9],
        [10, 11, 12]]])

相似的，`arr3d[1,0]`可以访问索引以(1,0)开头的那些值（以一维数组的形式返回）：

In [51]:
arr3d[1, 0]

array([7, 8, 9])

虽然是用两步进行索引的，表达式是相同的：

In [52]:
x = arr3d[1]
x[0]

array([7, 8, 9])

> **注意：**在上面所有这些选取数组子集的例子中，返回的数组都是视图。

### 4.1.5 切片索引

ndarray的切片语法跟Python列表这样的一维对象差不多：

In [53]:
arr

array([ 0,  1,  2,  3,  4, 64, 64, 64,  8,  9])

In [54]:
arr[1:6]

array([ 1,  2,  3,  4, 64])

对于之前的二维数组`arr2d`，其切片方式稍显不同：

In [55]:
arr2d

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [56]:
arr2d[:2]

array([[1, 2, 3],
       [4, 5, 6]])

可以看出，它是沿着第0轴（即第一个轴）切片的。也就是说，切片是沿着一个轴向选取元素的。表达式`arr2d[:2]`可以被认为是“选取arr2d的前两行”。

你可以一次传入多个切片，就像传入多个索引那样：

In [57]:
arr2d[:2, 1:]

array([[2, 3],
       [5, 6]])

像这样进行切片时，只能得到相同维数的数组视图。通过将整数索引和切片混合，可以得到低维度的切片。

例如，可以选取第二行的前两列：

In [58]:
arr2d[1, :2]

array([4, 5])

相似的，还可以选择第三列的前两行：

In [59]:
arr2d[:2, 2]

array([3, 6])

下图对此进行了说明：

![二维数组切片](https://upload-images.jianshu.io/upload_images/7178691-9da32d2f4629c304.png?imageMogr2/auto-orient/strip%7CimageView2/2/w/700)

注意，“只有冒号”表示选取整个轴，因此你可以像下面这样只对高维轴进行切片：

In [60]:
arr2d[:, :1]

array([[1],
       [4],
       [7]])

自然，对切片表达式的赋值操作也会被扩散到整个选区：

In [61]:
arr2d[:2, 1:] = 0
arr2d

array([[1, 0, 0],
       [4, 0, 0],
       [7, 8, 9]])

### 4.1.6 布尔型索引

来看这样一个例子，假设我们有一个用于存储数据的数组以及一个存储姓名的数组（含有重复项）。在这里，我将使用`numpy.random`中的`randn`函数生成一些正态分布的随机数据：

In [62]:
names = np.array(['Bob', 'Joe', 'Will', 'Bob', 'Will', 'Joe', 'Joe'])
names

array(['Bob', 'Joe', 'Will', 'Bob', 'Will', 'Joe', 'Joe'], dtype='<U4')

In [63]:
data = np.random.randn(7, 4)
data

array([[-0.30373489, -0.62047693, -0.94008236,  1.17974153],
       [-0.97736105,  0.25068476, -0.21141238, -0.19774226],
       [-0.53482336,  0.44176968, -0.04025335, -0.58253447],
       [-0.13330714, -0.18668794,  1.07329267,  1.08788782],
       [ 0.38316428, -0.98224222,  0.73896565,  1.10468182],
       [ 0.77223174, -0.20330717,  0.57210736, -0.94215615],
       [-1.21948456, -0.99742466,  0.1079735 ,  0.79659244]])

假设每个名字都对应`data`数组中的一行，而我们想要选出对应于名字`"Bob"`的所有行。跟算术运算一样，数组的比较运算（如==）也是矢量化的。因此，对`names`和字符串`"Bob"`的比较运算将会产生一个布尔型数组：

In [65]:
names == 'Bob'

array([ True, False, False,  True, False, False, False])

这个布尔型数组可用于数组索引：

In [66]:
data[names == 'Bob']

array([[-0.30373489, -0.62047693, -0.94008236,  1.17974153],
       [-0.13330714, -0.18668794,  1.07329267,  1.08788782]])

布尔型数组的长度必须跟被索引的轴长度一致。此外，还可以将布尔型数组跟切片、整数（或整数序列）混合使用：

In [67]:
data[names == 'Bob']

array([[-0.30373489, -0.62047693, -0.94008236,  1.17974153],
       [-0.13330714, -0.18668794,  1.07329267,  1.08788782]])

> **注意：**如果布尔型数组的长度不对，布尔型选择就会出错，因此一定要小心。

下面的例子，我选取了`names == 'Bob'`的行，并索引了列：

In [68]:
data[names == 'Bob', 2:]

array([[-0.94008236,  1.17974153],
       [ 1.07329267,  1.08788782]])

In [69]:
data[names == 'Bob', 3]

array([1.17974153, 1.08788782])

要选择除`"Bob"`以外的其他值，既可以使用不等于符号（!=），也可以通过`~`对条件进行否定：

In [70]:
names != 'Bob'

array([False,  True,  True, False,  True,  True,  True])

In [71]:
data[~(names == 'Bob')]

array([[-0.97736105,  0.25068476, -0.21141238, -0.19774226],
       [-0.53482336,  0.44176968, -0.04025335, -0.58253447],
       [ 0.38316428, -0.98224222,  0.73896565,  1.10468182],
       [ 0.77223174, -0.20330717,  0.57210736, -0.94215615],
       [-1.21948456, -0.99742466,  0.1079735 ,  0.79659244]])

`~`操作符用来反转条件很好用：

In [72]:
cond = names == 'Bob'
data[~cond]

array([[-0.97736105,  0.25068476, -0.21141238, -0.19774226],
       [-0.53482336,  0.44176968, -0.04025335, -0.58253447],
       [ 0.38316428, -0.98224222,  0.73896565,  1.10468182],
       [ 0.77223174, -0.20330717,  0.57210736, -0.94215615],
       [-1.21948456, -0.99742466,  0.1079735 ,  0.79659244]])

选取这三个名字中的两个需要组合应用多个布尔条件，使用`&`（和）、`|`（或）之类的布尔算术运算符即可：

In [73]:
mask = (names == 'Bob') | (names == 'Will')
mask

array([ True, False,  True,  True,  True, False, False])

In [74]:
data[mask]

array([[-0.30373489, -0.62047693, -0.94008236,  1.17974153],
       [-0.53482336,  0.44176968, -0.04025335, -0.58253447],
       [-0.13330714, -0.18668794,  1.07329267,  1.08788782],
       [ 0.38316428, -0.98224222,  0.73896565,  1.10468182]])

通过布尔型索引选取数组中的数据，将总是创建数据的副本，即使返回一模一样的数组也是如此。

>**注意：**Python关键字`and`和`or`在布尔型数组中无效。要是用`&`与`|`。

通过布尔型数组设置值是一种经常用到的手段。为了将data中的所有负值都设置为0，我们只需：

In [77]:
data[data < 0] = 0
data

array([[7.        , 7.        , 7.        , 7.        ],
       [0.        , 0.25068476, 0.        , 0.        ],
       [7.        , 7.        , 7.        , 7.        ],
       [7.        , 7.        , 7.        , 7.        ],
       [7.        , 7.        , 7.        , 7.        ],
       [0.77223174, 0.        , 0.57210736, 0.        ],
       [0.        , 0.        , 0.1079735 , 0.79659244]])

通过一维布尔数组设置整行或列的值也很简单：

In [76]:
data[names != 'Joe'] = 7
data

array([[7.        , 7.        , 7.        , 7.        ],
       [0.        , 0.25068476, 0.        , 0.        ],
       [7.        , 7.        , 7.        , 7.        ],
       [7.        , 7.        , 7.        , 7.        ],
       [7.        , 7.        , 7.        , 7.        ],
       [0.77223174, 0.        , 0.57210736, 0.        ],
       [0.        , 0.        , 0.1079735 , 0.79659244]])

后面会看到，这类二维数据的操作也可以用pandas方便的来做。

### 4.1.7 花式索引

花式索引（Fancy indexing）是一个NumPy术语，它指的是利用整数数组进行索引。假设我们有一个8×4数组：

In [78]:
arr = np.empty((8, 4))

for i in range(8):
    arr[i] = i
    
arr

array([[0., 0., 0., 0.],
       [1., 1., 1., 1.],
       [2., 2., 2., 2.],
       [3., 3., 3., 3.],
       [4., 4., 4., 4.],
       [5., 5., 5., 5.],
       [6., 6., 6., 6.],
       [7., 7., 7., 7.]])

为了以特定顺序选取行子集，只需传入一个用于指定顺序的整数列表或ndarray即可:

In [79]:
arr[[4, 3, 0, 6]]

array([[4., 4., 4., 4.],
       [3., 3., 3., 3.],
       [0., 0., 0., 0.],
       [6., 6., 6., 6.]])

这段代码确实达到我们的要求了！使用负数索引将会从末尾开始选取行：

In [80]:
arr[[-3, -5, -7]]

array([[5., 5., 5., 5.],
       [3., 3., 3., 3.],
       [1., 1., 1., 1.]])

一次传入多个索引数组会有一点特别。它返回的是一个一维数组，其中的元素对应各个索引元组：

In [81]:
arr = np.arange(32).reshape((8, 4))
arr

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15],
       [16, 17, 18, 19],
       [20, 21, 22, 23],
       [24, 25, 26, 27],
       [28, 29, 30, 31]])

In [82]:
arr[[1, 5, 7, 2], [0, 3, 1, 2]]

array([ 4, 23, 29, 10])

最终选出的是元素(1,0)、(5,3)、(7,1)和(2,2)。无论数组是多少维的，花式索引总是一维的。

这个花式索引的行为可能会跟某些用户的预期不一样，选取矩阵的行列子集应该是矩形区域的形式才对。下面是得到该结果的一个办法：

In [85]:
arr[[1, 5, 7, 2]][:, [0, 3, 1, 2]]

array([[ 4,  7,  5,  6],
       [20, 23, 21, 22],
       [28, 31, 29, 30],
       [ 8, 11,  9, 10]])

记住，花式索引跟切片不一样，它总是将数据复制到新数组中。

### 4.1.8 数组转置和轴对换

转置是重塑的一种特殊形式，它返回的是源数据的视图（不会进行任何复制操作）。数组不仅有transpose方法，还有一个特殊的T属性：

In [86]:
arr = np.arange(15).reshape((3, 5))
arr

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14]])

In [87]:
arr.T

array([[ 0,  5, 10],
       [ 1,  6, 11],
       [ 2,  7, 12],
       [ 3,  8, 13],
       [ 4,  9, 14]])

在进行矩阵计算时，经常需要用到该操作，比如利用`np.dot`计算矩阵内积：

In [88]:
arr = np.random.randn(6, 3)
arr

array([[-0.83925332,  0.75099479, -1.14641023],
       [ 0.67485401, -1.1621178 , -1.73183121],
       [-0.46070343, -0.27902639,  1.0680805 ],
       [-1.76873152, -1.54058096, -0.97731626],
       [-0.22146835, -1.18885784,  0.49500509],
       [-0.36997842,  0.41546365,  0.6687977 ]])

In [89]:
np.dot(arr.T, arr)

array([[4.68636518, 1.54846961, 0.67286841],
       [1.54846961, 5.95174938, 2.04862639],
       [0.67286841, 2.04862639, 7.10175919]])

对于高维数组，transpose需要得到一个由轴编号组成的元组才能对这些轴进行转置（比较费脑子）：

In [90]:
arr = np.arange(16).reshape((2, 2, 4))
arr

array([[[ 0,  1,  2,  3],
        [ 4,  5,  6,  7]],

       [[ 8,  9, 10, 11],
        [12, 13, 14, 15]]])

In [91]:
arr.transpose((1, 0, 2))

array([[[ 0,  1,  2,  3],
        [ 8,  9, 10, 11]],

       [[ 4,  5,  6,  7],
        [12, 13, 14, 15]]])

这里，第一个轴被换成了第二个，第二个轴被换成了第一个，最后一个轴不变。

简单的转置可以使用`.T`，它其实就是进行轴对换而已。ndarray还有一个`swapaxes`方法，它需要接受一对轴编号：

In [92]:
arr

array([[[ 0,  1,  2,  3],
        [ 4,  5,  6,  7]],

       [[ 8,  9, 10, 11],
        [12, 13, 14, 15]]])

In [93]:
arr.swapaxes(1, 2)

array([[[ 0,  4],
        [ 1,  5],
        [ 2,  6],
        [ 3,  7]],

       [[ 8, 12],
        [ 9, 13],
        [10, 14],
        [11, 15]]])

swapaxes也是返回源数据的视图（不会进行任何复制操作）。

## 4.2 通用函数：快速的元素级数组函数